//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuhamediarpvISP_19
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaEkzamenEntities : DbContext
    {
        public static BazaEkzamenEntities _context;
        public BazaEkzamenEntities()
            : base("name=BazaEkzamenEntities")
        {
        }

        public static BazaEkzamenEntities GetContext()
        {
            if (_context == null)
                _context = new BazaEkzamenEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tablica_Ekzamen> Tablica_Ekzamen { get; set; }
    }
}
